### ISSUE TITLE
Update to 3.1.x

### ISSUE THREAD

**Issue by AndreasGerken** [bolt/bolt-extension-robots#2]
Hi Gawain,
could you release a version for 3.1.x? For now i will create my own robots.txt but the extension could be very helpful!

Thanks and cheers

**Comment by GwendolenLynch** [comment]
Hi Andreas,

The current version has the `"require"` set to `"bolt/bolt": "^3.0"` so is already compatible … However, I have yet to tag a release so you would need (at this moment) to do two things to install it:
1. In your `app/config/config.yml` file around [here](https://github.com/bolt/bolt/blob/release/3.1/app/config/config.yml.dist#L389-L393) you want to set `minimum-stability` to `dev` and `prefer-stable` to `true` , e.g.

```
extensions:
    composer:
        minimum-stability: dev
        prefer-stable: true
```
1. In the dialogue where you select the version to install, under "_Unstable test versions_" select:

```
bolt/robots 3.0.x-dev
```

**Comment by AndreasGerken** [comment]
You're so fast :)
i managed to install it with this:

> extensions:
>   site: 'https://extensions.bolt.cm/'
>   enabled: true
>   stability: dev
>   composer:
>     minimum-stability: dev      # Either 'stable', 'beta', or 'dev'. Setting 'dev' will allow you to install dev-master versions of extensions.
>     prefer-stable: true            # Prefer stable releases over development ones

But now i don't really know how to activate it :) could you come to irc for a second?

**Comment by GwendolenLynch** [comment]
Sorted … the remaining question was the "missing" config file … for other readers, Bolt only accesses config files on use … at which point it also checks if one exists, and copies the default one into `app/config/extensions/` if needed.

Yes, we need to improve this in Bolt itself :smile:

**Comment by ucay** [comment]
> Sorted … the remaining question was the "missing" config file …

it isn't missing, just wrong default filename. (PR #3)

**Comment by GwendolenLynch** [comment]
Lovely, even tagged a stable release. Thanks @ucay
